### ISSUE TITLE
Rename Quality by Design to Session Insights

### ISSUE THREAD

**Issue by benhepworth** [camaraproject/APIBacklog#116]
**Problem description**
Rename the Quality by Design repo to Session Insights

**Expected action**
This repo: https://github.com/camaraproject/QualityByDesign
Should become: https://github.com/camaraproject/SessionInsights

**Additional context**
There are two current open PRs in QualityByDesign that we are working on closing (README updates and User Story). Herbert suggested these get merged before the rename happens. I will udpate this issue once they have been merged so the rename can move forward.

**Comment by benhepworth** [comment]
hi @hdamker - I think we're ready for the rename now. All of the PRs in the Quality by Design repo have been approved and merged. I also opened a PR (#117) in APIBacklog that maps to this issue (for the updating of the original proposal docs to reflect the new name). Will you be the one to perform the rename or do I need to ping someone in APIBacklog?

**Comment by hdamker** [comment]
Hi @benhepworth, is see the following next steps, @jgarciahospital to correct/add:

- [ ] Short approval of the name change by the API Backlog team (or just @jgarciahospital)
- [ ] Renaming of the repository (CAMARA admins, I will take that)
- [ ] Approval and merge of #117 
- [ ] PR on the APIBacklog.md (most probably in batch PR after the next API Backlog meeting)

As SessionInsights is part of ConnectivityInsights, that should be it all.

**Comment by benhepworth** [comment]
FYI here is the link to the Connectivity Insights Meeting where the new name was agreed upon: https://lf-camaraproject.atlassian.net/wiki/x/mIDoAQ

**Comment by hdamker** [comment]
Renaming of repository done, see https://github.com/camaraproject/APIBacklog/pull/117#issuecomment-2494755063.
