### ISSUE TITLE
New API Proposal - Facial Recognition

### ISSUE THREAD

**Issue by YmFuWrok** [camaraproject/APIBacklog#126]
Proposal to create a "Facial Recognition" API:

This API is built on the concept of “1 platform + 1 set of facial recognition capabilities + N applications” which is based on integration, innovation, and openness.  

The target of this API is focus on high-quality facial detection, high-performance face comparison, and multi-modal liveness detection to build a more convenient, efficient, and accurate security barrier.

**Comment by Kevsy** [comment]
HI @YmFuWrok , thanks for your proposal.  I have a question regarding the PR text:

"We offer unified APIs, H5, and SDKs to provide facial recognition services"

Please can you clarify 'H5'? Do you mean an `.h5` file (HDF5 Hierarchical Data Format representation)?

**Comment by YmFuWrok** [comment]
HI @Kevsy , H5 here refers to HTML5. We provide a JavaScript-based SDK for users to develop facial data collection on the client side. The collected facial data is then sent to our backend services for facial recognition and related analysis. This is distinct from the native Android and iOS SDKs.

**Comment by eric-murray** [comment]
@YmFuWrok
I think this proposal would be best handled as a scope enhancement to the existing [Model as a Service](https://github.com/camaraproject/APIBacklog/blob/main/documentation/API%20proposals/APIFamily_Proposal_MaaS_ChinaMobile.md) sub-project. Can you consider that and, if you agree, complete the [API sub-project scope enhancement template](https://github.com/camaraproject/APIBacklog/blob/main/documentation/API-Scope-Enhancement-Template.md) instead?

Thanks

**Comment by YmFuWrok** [comment]
@eric-murray Thank you for your suggestion. We will carefully consider it.
