### ISSUE TITLE
New API Proposal - Energy Footprint Notification

### ISSUE THREAD

**Issue by FabrizioMoggio** [camaraproject/APIBacklog#141]
The Energy Footprint Notification (EFN) API provides, to the API Consumer, information about the E2E energy consumption and Carbon Footprint for a specified service that is provided by a certain number of active instances of an application. The applications that are monitored for their energy consumption are the ones managed by the Operator and that run on top of the Operator’s infrastructure. 

The service is deployed and managed via the Telco Platform, for this reason the Telco Platform is aware of all the active instances supporting that service and it is also aware of the energy consumption in the Data Centers hosting the application instances providing the service. RAN and Core Network are deeply involved in the service provisioning, so their energy consumption is relevant to have and E2E comprehensive view.

The EFN API is an intent based API that can be invoked expressing the following intent “What was the energy consumption from a Service in this period of time?”.

**Comment by hdamker** [comment]
@jgarciahospital as this proposal is approved as Sandbox: do you want to create an onboarding issue and closing here?

**Comment by jgarciahospital** [comment]
> @jgarciahospital as this proposal is approved as Sandbox: do you want to create an onboarding issue and closing here?

Created in #165
