### ISSUE TITLE
New API Proposal - Tenure

### ISSUE THREAD

**Issue by eric-murray** [camaraproject/APIBacklog#2]
Tenure API proposal from GSMA OGW Drop 4:

Establish a level of trust against mobile ID by verifying the length of tenure for a mobile user bound to a mobile number; tenure means the period of time a MSISDN has been associated with a specific user. API checks whether the lifetime tenure of a given MSISDN is longer than an input date.: Enterprises can use Tenure API to gauge and establish a level of trust (or Trust Score) with a mobile user who is associated with a specific mobile number, based on how long they have been associated with that number.

API PR is #1. This includes example YAML.

Submitted on behalf of Ali Gilani (@ag-vodafone)

**Comment by hdamker** [comment]
> period of time a MSISDN has been associated with a specific user.

Question: what is the answer of the API if the MSISDN has been associated longterm with a specific user, but the MSISDN has only recently ported by the user to the current communication service provider? If the answer is in this cases is "false", I recommend to change the description as it is not correct. If the answer if "true", and the porting of number will not break the tenure, I would be interested how this could be implemented.

**Comment by ag-vodafone** [comment]
This proposed spec does not cater to porting. Therefore, the API would be establishing a level of trust against the mobile ID by verifying the length of tenure for a mobile user bound to the MSISDN. In this case - Tenure should mean the period of time a MSISDN has been associated with specific user with their current mobile operator.

**Comment by bigludo7** [comment]
Hello @eric-murray @TEF-RicardoSerr 
You can count on Orange as supporter for this one.
Sorry for the late answer.

**Comment by TEF-RicardoSerr** [comment]
Hello @ag-vodafone, @bigludo7, @jgarciahospital, @NoelWirzius, @ToshiWakayama-KDDI 

As for [16-05 TSC Minutes](https://wiki.camaraproject.org/display/CAM/2024-05-16+TSC+Minutes) the API is approved and I need you to provide the initial maintainers and codeowners from your side for the Tenure GitHub Repository

**Comment by jgarciahospital** [comment]
https://github.com/claraserranosolsona & https://github.com/jgarciahospital from Telefonica.

**Comment by ag-vodafone** [comment]
Hi @TEF-RicardoSerr,

From Vodafone, it will be myself (@ag-vodafone) and @eric-murray as we both have been involved in submitting the proposal.

**Comment by NoelWirzius** [comment]
Again as comment: https://github.com/grgpapadopoulos and myself @NoelWirzius

**Comment by bigludo7** [comment]
For Orange https://github.com/GillesInnov35 and myself @bigludo7

**Comment by TEF-RicardoSerr** [comment]
Tenure group is seted up as Codeowners and maintainers files have been merged. This issue can be closed
