### ISSUE TITLE
New Proposal - Customer Premise Equipment Management

### ISSUE THREAD

**Issue by caubut-charter** [camaraproject/APIBacklog#21]
This API manages fixed devices provided by network operators that reside at customer premises.  The core functionality includes requesting service sites and devices associated with a customer account, managing Wi-Fi BSSs, and rebooting devices.

The API is designed to support simple use cases, such as allowing a developer to set up a guest Wi-Fi network, and more complex use cases, such as allowing management of multiple devices across several service sites.  The design also allows for extension to support future use cases such as setting up Thread networks or managing mobile hot-spots not attached to a service site.

We have chosen to use the terminology “Customer Premise Equipment” (CPE) but are open to the use of a different term. Due to some of the complexities regarding potential naming conventions this API could support (e.g., router, switch, access point, modem, fixed wireless, gateway, border router, devices that support multiple functions, etc.), we felt it best to work with CAMARA to address proper terminology.

[yaml - GitHub](https://github.com/caubut-charter/WorkingGroups/blob/feat/api-proposal-cpe-mgmt/APIBacklog/documentation/SupportingDocuments/others/cpe-management-api.yaml) - [yaml - Swagger Editor](https://editor.swagger.io/?url=https://raw.githubusercontent.com/caubut-charter/WorkingGroups/feat/api-proposal-cpe-mgmt/APIBacklog/documentation/SupportingDocuments/others/cpe-management-api.yaml) - [slides - GitHub](https://github.com/caubut-charter/WorkingGroups/blob/feat/api-proposal-cpe-mgmt/APIBacklog/documentation/SupportingDocuments/others/cpe-management-api.pptx)

**Comment by TEF-RicardoSerr** [comment]
GitHub Repository have been created [here](https://github.com/camaraproject/NetworkAccessManagement), this issue can be closed

**Comment by hdamker** [comment]
@TEF-RicardoSerr APIBacklog.md need to be updated as well.
