### ISSUE TITLE
New Proposal - Capability and Runtime Restrictions

### ISSUE THREAD

**Issue by gmuratk** [camaraproject/APIBacklog#22]
CAMARA Service APIs are designed with many optional parameters and features.  It’s unreasonable to expect each API Producer (i.e. Operator) to support all these optional parameters.  In addition, some supported features and parameters may not be enabled at Service API invocation time, based on network state, who might be invoking and/or for whom/which device, location, …)  There is currently no mechanism to exchange such information with API Consumers (i.e. Application Service Providers (ASP)/Developers/Aggregators) and keep the CAMARA APIs the same across the Exposure Gateways.

This API proposes reuse of JSON schema to communicate 'limits' enforced by API Producer/Provider to developers.

**Comment by gmuratk** [comment]
@jgarciahospital as time ran out in the API Backlog call yesterday (Sept 26, 2024), I couldn't provide an update.  Given the alternate timing of the meetings, I'll not be able to join until the following meeting.  Please find the couple slides providing an update embedded in the API Backlog Minutes:  [Capabilities_and_Runtime_Restrictions_Update.pptx ](https://lf-camaraproject.atlassian.net/wiki/spaces/CAM/pages/14561812/2024-09-26+API+backlog+minutes)

We request this proposal to be taken to TSC for request of 'sandbox' creation?

**Comment by jgarciahospital** [comment]
Hi Murat, 

As proposal was already considered and approved in backlog to be proposed to TSC, I don't see any problem on pushing it this thursday. Please confirm your presence on the next TSC (3rd October, 10-11:30 CET/UTC+2)

**Comment by gmuratk** [comment]
> Hi Murat,
> 
> As proposal was already considered and approved in backlog to be proposed to TSC, I don't see any problem on pushing it this thursday. Please confirm your presence on the next TSC (3rd October, 10-11:30 CET/UTC+2)

Thank you, Jorge. Unfortunately, I can't commit to this week's TSC, but I can be there at the next TSC, I believe on October 17th).

**Comment by jgarciahospital** [comment]
Perfect! I take note of it.

**Comment by jgarciahospital** [comment]
Hi @gmuratk, can you upload in the PR #74 the documentation included in those minutes? The folder https://github.com/camaraproject/APIBacklog/tree/main/documentation/SupportingDocuments is a good place for it.
