### ISSUE TITLE
Scope change for QoD API - Enhancement with provision mode

### ISSUE THREAD

**Issue by jgarciahospital** [camaraproject/APIBacklog#26]
As evolution of the existing QoD API, provision mode is proposed to enhance current API.

Issue raised in backlog group since it modifies original API scope.

https://github.com/camaraproject/WorkingGroups/pull/403

**Comment by TEF-RicardoSerr** [comment]
This issue is currently being followed up within [camaraproject/QualityOnDemand issue#268](https://github.com/camaraproject/QualityOnDemand/issues/268) I believe this can be closed and reopened if you reach up to another dead end point regarding scope. @hdamker @jgarciahospital

**Comment by hdamker** [comment]
I agree on closing the issue here.
