### ISSUE TITLE
New API proposal-Verified Caller

### ISSUE THREAD

**Issue by DanXu-ChinaTelecom** [camaraproject/APIBacklog#27]
This API allows accurate operator-certified "Verified Caller" information, including SMS and video clips, to be displayed on the phone screen of the called user before they answer the call. This API enables enterprise customers to vividly present their multimedia business cards and reduces the incidence of malicious calls. 

It is applicable to customers in industries such as government, finance, express delivery, healthcare, education, etc., who have outbound call requirements. 
For instance, when a hospital arranges follow-ups and communication between customer service and rehabilitation patients, patients might doubt the hospital's identity and typically refuse the calls. By utilizing this API, the hospital's identity can be displayed, thereby improving connection rates and significantly enhancing customer service satisfaction.

**Comment by TEF-RicardoSerr** [comment]
Supporting material available [here](https://github.com/camaraproject/APIBacklog/blob/main/documentation/SupportingDocuments/Verified%20Caller%20API%20Introduction.pptx)

**Comment by TEF-RicardoSerr** [comment]
Hello @DanXu-ChinaTelecom, @Jason-ZTE 

As for [16-05 TSC Minutes](https://wiki.camaraproject.org/display/CAM/2024-05-16+TSC+Minutes) the API is approved and I need you to provide the initial maintainers and codeowners from your side for the upcoiming Verified Caller GitHub Repository

**Comment by DanXu-ChinaTelecom** [comment]
thx @TEF-RicardoSerr ，we proposed initial codeowners： DanXu-ChinaTelecom and Jason-ZTE @Jason-ZTE ，

and  initial maintainers as follows：

| Org           | Name           | GitHub Username    |
| ------------- | -------------- | ------------------ |
| China Telecom | Dan Xu         | DanXu-ChinaTelecom |
| China Telecom | Xianyang Zhang | zxyxwz           |
| ZTE | Tu Jiashun | Jason-ZTE |
| China Unicom  | Yang Fan       | chinaunicomyangfan |
| China Mobile  | Hanbai Wang    | HanbaiWang         |
| HuaWei | Shuting Qing  | ShutingQing   |
| Whale Cloud Technology Co.,Ltd   | Yun Wang   | WangYunyunA |

**Comment by TEF-RicardoSerr** [comment]
Subproject have been created [here](https://github.com/camaraproject/VerifiedCaller). Closing this issue
