### ISSUE TITLE
NEW API Proposal _ Device Data Volume 

### ISSUE THREAD

**Issue by NoelWirzius** [camaraproject/APIBacklog#28]
This API offers detailed insights into the customer's data usage status, including whether they have remaining data volume available and their current position within that volume allocation. It accurately determines whether the customer is nearing the beginning or the end of their allocated data volume, providing valuable information for managing data usage efficiently.

The Api is one of the KPIs for the API Proposal Device Quality Indicator

PR can be find her: camaraproject/WorkingGroups#411

**Comment by TEF-RicardoSerr** [comment]
@NoelWirzius Can you please make the PR in this [new APIBacklog path](https://github.com/camaraproject/APIBacklog/tree/main/documentation/API%20proposals)

**Comment by NoelWirzius** [comment]
PR: #39

**Comment by TEF-RicardoSerr** [comment]
Hello Noel. As spoken in the last meeting I need you to find support (at least from another company) for the proposed APIs before moving to TSC.

**Comment by QaunainM** [comment]
Vonage supports this API. It would compliment and enable a range of the other CAMARA APIs and capabilities.

**Comment by eric-murray** [comment]
@TEF-RicardoSerr
This issue can be closed
