### ISSUE TITLE
New API proposal-Call Status API

### ISSUE THREAD

**Issue by questsin** [camaraproject/APIBacklog#29]
## Redacted

**Comment by NoelWirzius** [comment]
Hey please check the discussions in the tsc for scam signal - it is looking as it is the same api. What are the differences? 
In this meeting minutes there are more infos: 
https://github.com/camaraproject/Governance/blob/bf164cb92c2c0ec50201328d77c3d1a4fd7b10a8/documentation/MeetingMinutes/TSC/TSC-2023-09-21-Meeting-Minutes.md?plain=1#L90

**Comment by questsin** [comment]
Redacted API as it already a proposal on another Bodies Forum

**Comment by eric-murray** [comment]
@questsin Can you close this issue? Thanks.

**Comment by TEF-RicardoSerr** [comment]
As spoken in meeting 23/may
