### ISSUE TITLE
New API proposal-Shutdown Service Status

### ISSUE THREAD

**Issue by chinaunicomyangfan** [camaraproject/APIBacklog#33]
This API allows users to obtain the current shutdown status of a certain phone number, including Voice/SMS in shutdown, Voice/SMS out shutdown, and data service shutdown.
Anti fraud: When receiving SMS or phone calls from a suspended number, it may be a disguised fraudulent number, which can provide security risk alerts.
Customer service support: If a user reports that they are unable to receive calls or text messages, customer service personnel can determine whether the problem is caused by the phone voice function being shut down by checking the phone's status.
This is from GSMA drop4 priority list
PR is here:[32](https://github.com/camaraproject/APIBacklog/pull/32)

**Comment by TEF-RicardoSerr** [comment]
Let me close this issue as I have migrated the existing one to keep the record of the conversation, thank you @chinaunicomyangfan
