### ISSUE TITLE
New API proposal-Subscription Status

### ISSUE THREAD

**Issue by chinaunicomyangfan** [camaraproject/APIBacklog#34]
This API allows users to obtain the current subscription status of a certain phone number, including the subscription of Voice/SMS in, Voice/SMS out, and data service.
Payment System and Risk Management: In scenarios where payment or identity verification relies on phone numbers, such as e-commerce platforms or financial service providers, this API can be used to verify whether user accounts are functioning properly. This helps to reduce fraud and payment risks, ensuring that only normal accounts can conduct transactions.
Customer Service Support: If a user reports that they are unable to receive calls or text messages, customer service personnel can determine whether the problem is caused by the phone voice function being shut down by checking the phone's status.
This is from GSMA drop4 priority list
PR is here: [32](https://github.com/camaraproject/APIBacklog/pull/32)

**Comment by chinaunicomyangfan** [comment]
Based on the results of the [discussion about the overlap between ShutdownStatus and DeviceStatus](https://github.com/camaraproject/DeviceStatus/issues/167) in Device Status .I believe they are two different APIs.
Additionally, based on the suggestions discussed, I think changing the name to SubscriptionStatus would be more accurate.

**Comment by jgarciahospital** [comment]
As agreed in the group discussion (please correct if mistaking):

- Shutdown Service pending to create repo. Backlog admins will get in touch with API supporters to find CodeOwner/Maintainers, and will follow similar strategy as previous APIs. Name change to be confirmed (Subscription Status).

As agreed in the conversation, KYC family meetings can be used as follow-up tracker for the hole set of APIs (KYC-Match, KYC-Fill-In, Age Verification, Tenure, Number Recycling, Shutdown Service, final decision on meetings will take place after some running time. 

@camaraproject/api-backlog_maintainers

**Comment by eric-murray** [comment]
@TEF-RicardoSerr
This issue can be closed

**Comment by TEF-RicardoSerr** [comment]
Please @chinaunicomyangfan collect the codeowners and maintainers from your side and from Huawei and China Telecom

**Comment by chinaunicomyangfan** [comment]
@TEF-RicardoSerr  I have already sent the codeowner and maintainer list of Subscription Status via email. I am not sure if you have received the email, so I just sent it again.My colleague ShuoRan will serve as the owner to undertake the related work of this API.
Here is the list of personnel:
@ShuoRan ChinaUnicom is the code owner from ChinaUnicom
@philipxujin  is the maintainer from Huawei.
@DanXu-ChinaTelecom is the maintainer from China Telecom.
