### ISSUE TITLE
Move Simple Edge Discovery to own repository

### ISSUE THREAD

**Issue by Kevsy** [camaraproject/APIBacklog#37]
**Problem description**
Simple Edge Discovery needs to move into its own repository for release tracking, as the other Edge Cloud APIs are at different versions. 

**Expected action**

Per minutes of Technical Steering Committee 02-May-24, "Request to [Kevin Smith](https://wiki.camaraproject.org/display/~kevsy) to create a specific repository for SimpleEdgeDiscovery API from Edge Cloud project."

@hdamker please may I ask you to create the repository?

Name: Simple Edge Discovery
Initial codeowners and maintainers:  @kevsy @crissancas  @javierlozallu

**Additional context**

**Comment by hdamker** [comment]
@Kevsy Thanks for opening the issue. I will create the repository - I assume that the API will be still managed within the EdgeCloud API family, so no new wiki page, mailing list, and meeting. Just the repository is needed. Ok?

**Comment by Kevsy** [comment]
Thanks @hdamker , yes that's fine

**Comment by hdamker** [comment]
@Kevsy Repository created, please review and merge: 
* https://github.com/camaraproject/SimpleEdgeDiscovery/pull/1
* https://github.com/camaraproject/SimpleEdgeDiscovery/pull/2

@crissancas @javierlozallu Please accept the invite which you have received to get a member of the camaraproject organization. Only then will the CODEOWNERS file get valid.

**Comment by javierlozallu** [comment]
@hdamker we have just accepted the invitation. Thank you!

**Comment by TEF-RicardoSerr** [comment]
Guess we can close this issue according to pas meeting [minutes 9/may](https://wiki.camaraproject.org/x/cAGCAQ)

**Comment by eric-murray** [comment]
Closing issue
