### ISSUE TITLE
Scope change for KYC-Match API - Scoring Logic

### ISSUE THREAD

**Issue by jgarciahospital** [camaraproject/APIBacklog#45]
As evolution of the existing KYC-Match API, scoring logic is proposed to be included:

Current KYC-Match service validates if the information reported by the developer matches with the information that the operator has registered in its systems. Scoring proposal (aka fuzzy logic) is proposed to allow a wider response in which, for the current "false" responses, it will provide a scoring of how close to the actual value is the requested field. <br> <br> E.g. if developer is reporting the name "Clara" while the registered name by operator is "Carla". User may have suffered a typo, and currently the API will directly respond "false", while the scoring mechanism will also report that the requested name is 88% close to the actual name.

Issue raised in backlog group since it modifies original API scope.

PR #46

**Comment by ToshiWakayama-KDDI** [comment]
Hi Jorge,

Looks good to me, except for one point.  According to related discussions in KnowYourCustomer SP, some operators and markets (including Japan) do not need 'Scoring' for KYC Match, so, the enhanced Match API should be able to work without Scoring.  If you could add this point to the template, it would be much appreciated.

Or, should I make this comment in PR?  I will do this, just in case.

Best regards,
Toshi

**Comment by ToshiWakayama-KDDI** [comment]
Hi Jorge,

Sorry, I have some questions.  Is this new API proposal?  Because API Family is KYC Match Scoring.  I do not understand the relationship with existing KnowYourCustomer APIs.

Thanks.

**Comment by jgarciahospital** [comment]
Hi Toshi, as discussed during the meeting (https://wiki.camaraproject.org/display/CAM/2024-05-23+API+backlog+minutes):

- Proposal is to include this enhancement as a feature of the existing KYC-match API
(API proposal template will be updated to include the enhancement, instead of API family name)
- API parameter is to be proposed as optional, just because it only applies to some cases (non-numerical parameters with false response) and also to ensure retro-compatibility.
- API enhancement to be discussed in KYC SP, as in [KYC Issue#85](https://github.com/camaraproject/KnowYourCustomer/issues/85)

**Comment by ToshiWakayama-KDDI** [comment]
Hi Jorge,

Thanks.  Same understanding.  I don't think we could ensure minute detail of your proposed template in PR #46, but it seems it is generally in line with our discussion so far in our Issue #85, so, we will continue our discussion taking your proposal into consideration.  And, as we all know, Telefonica and Vodafone members are involved in KYC SP.

Thanks.
Toshi

**Comment by jgarciahospital** [comment]
Issue to be closed

**Comment by eric-murray** [comment]
Closing issue
