### ISSUE TITLE
New Proposal-DeviceVisitLocation API

### ISSUE THREAD

**Issue by chinaunicomyangfan** [camaraproject/APIBacklog#5]
PR-https://github.com/camaraproject/WorkingGroups/pull/329

**Comment by TEF-RicardoSerr** [comment]
The Repository [LocationInsights](https://github.com/camaraproject/LocationInsights) have been created to cover https://github.com/camaraproject/APIBacklog/issues/5 and https://github.com/camaraproject/APIBacklog/issues/16. The issue can be closed

**Comment by hdamker** [comment]
@TEF-RicardoSerr APIBacklog.md need to be updated as well.
