### ISSUE TITLE
New API Proposal - Number Recycling

### ISSUE THREAD

**Issue by tcchiba** [camaraproject/APIBacklog#54]
Number Recycling API proposal from GSMA OGW Drop #4:

To know whether a phone number is linked to a subscriber, the Number Recycling API can be used to check whether the subscriber of the phone number has changed.
A common scenario is when a fraudster obtains a phone number that previously belonged to another person who did not properly deactivate or verify it. The fraudster can then use this number to commit identity theft or engage in fraudulent activities, such as obtaining access codes for accounts associated with that number. In some cases, fraudsters may also attempt to use services or avoid charges by leveraging old, no longer used numbers that were previously used by other users.

**Comment by james-emerson** [comment]
@tcchiba @hdamker 
How does this differ to 'Tenure' in the Know Your Customer Family? https://github.com/camaraproject/Tenure

**Comment by hdamker** [comment]
@james-emerson I'm not involved in the content discussion, I just transfer the issue into the right repository. 
But I heard the question already before ... cc: @NoelWirzius

**Comment by tcchiba** [comment]
@james-emerson, @hdamker, @TEF-RicardoSerr   

Comparing the Number Recycling API, Tenure API, and Shutdown Service Status API from the perspective of sample "Request", sample "Response", and "Purpose & Use Case", I think there are differences especially in the content and meaning of "Response".

**- Number Recycling API**
Whether the contract has been changed since the specified date of the request, or the date the current contract started

**- Tenure API**
Whether the contract period is longer than the period specified by the server side (plus billing segment information)

**- Shutdown Service Status API**
Whether the service was shut down at the time the API was requested

Even if there are some similarities in the request content and purpose, because of these differences, I think it would be better to develop each as a separate API in order to provide an API that is easy for application developers to understand.

---

### **Number Recycling API**

Option 1: Response regarding whether there will be changes from the specified date
**Request**: MSISDN, Specified Date ("value": "2019-01-15")
**Response**: Boolean (True/False - Contract change)

Option2: Response regarding the start date of the current contract
**Request**: MSISDN
**Response**: Contract Start Date

**Purpose & Use Case**:
- Check whether there has been a change in the subscriber associated with the specific phone number after the specified date.
- Also, enterprise/app service providers want to prevent mis-delivery before sending messages to customers.
- Furthermore, the enterprise may authenticate the user using SMS-OTP/phone as a means of account recovery. If the specific phone number is canceled and someone else is using it, the enterprise wants to prevent it from being reset.

### **Tenure API**

**Sample Request**: {"tenure_before_date":{"value": "2019-01-15"}}
**API Response**: True/False - if tenure is longer than specified date + billing segment (PAYG/PAYM/Business)
**Sample Response**: "tenure_before_date_check": true, "billing_segment": "PAYM"

Purpose & Use Case:
- Enterprises can use Tenure API to gauge and establish a level of trust (or Trust Score) with a mobile user who is associated with a specific mobile number, based on how long they have been associated with that number.
- To Establish level of trust (or Trust Score) against a mobile ID (MSISDN). The Tenure API will return a True or False answer as to whether the customer's tenure with an operator has been longstanding.
- Customer submits MSISDN to understand if the mobile number has been registered to a CSP for longer than a specific date.

### **Shutdown Service Status API**

**Request**: MSISDN
**Response**: Boolean (True/False - Service shutdown)

**Purpose & Use Case:**
 - This API allows users to obtain the current shutdown status of a certain phone number, including Voice/SMS in shutdown, Voice/SMS out shutdown, and data service shutdown.
 - Payment System and Risk Management: In scenarios where payment or identity verification relies on phone numbers, such as e-commerce platforms or financial service providers, this API can be used to verify whether user accounts are functioning properly. This helps to reduce fraud and payment risks, ensuring that only normal accounts can conduct transactions.
 - Customer Service Support: If a user reports that they are unable to receive calls or text messages, customer service personnel can determine whether the problem is caused by the phone voice function being shut down by checking the phone's status.
 - Operators can obtain the shutdown and resumption status of mobile network users by querying the information in the UDM/HSS contracted network element devices of the mobile network.

**Comment by tcchiba** [comment]
[20240627 KDDI Number Recycling.pptx](https://github.com/user-attachments/files/16011616/20240627.KDDI.Number.Recycling.pptx)

I uploded the slides for the above.

**Comment by NoelWirzius** [comment]
Hey @tcchiba thanks for this detailed overview. I see the "technology" difference between Number recovery/tenure, and fully agree that these is different. 

But by taking a look at the Use-Cases and the Customer needs i see there a overlap. This is where im thinking to put booth Apis more or less at least together in one working group or discuss this as one combined topic Number recycling & Tenure.

**Comment by QaunainM** [comment]
Btw, I've heard directly from a few large companies that they would instantly benefit from the Number Recycle solution. 

Its not so much the fraud use case that came up, but rather the legitimate users who've received a number that used to be assigned to a different person.

**Comment by eric-murray** [comment]
@TEF-RicardoSerr
This issue can be closed

**Comment by TEF-RicardoSerr** [comment]
@eric-murray @NoelWirzius @ToshiWakayama-KDDI 

Could you please provide the GitHUb users of the CODEOWNERS/Maintainers for [the created subgroup](https://github.com/camaraproject/NumberRecycling/blob/main/CODEOWNERS)? Please.

**Comment by ToshiWakayama-KDDI** [comment]
Thank you, @TEF-RicardoSerr ,
cc @eric-murray , @NoelWirzius 

From KDDI, pleaes include the following members:

- Codeowner: Masaharu Hattori (Masa8106)
- Maintainers: Masaharu Hattori (Masa8106),  Kenichi Yamamoto  (yamamoto0104)

Thanks and best regards.
Toshi

**Comment by ToshiWakayama-KDDI** [comment]
Hi @eric-murray , Hi @NoelWirzius , cc @patriciaserranog 

Could you please provide CODEOWNERS/Maintainers for NumberRecycling API from Vodafone and DT? 

Thanks,
Toshi
cc @Masa8106, @yamamoto0104

**Comment by eric-murray** [comment]
Hi @ToshiWakayama-KDDI

For Vodafone, please add the following:

CodeOwner: @eric-murray
Maintainer: @luislopezcorpas

Many thanks

**Comment by jgarciahospital** [comment]
First initial list of maintainers and codeowners included, pending from DT @NoelWirzius

**Comment by jgarciahospital** [comment]
CodeOwners included, issue to be solved
