### ISSUE TITLE
API Classification

### ISSUE THREAD

**Issue by marc196** [camaraproject/APIBacklog#6]
API classification is a correct approach if Class are mutually exclusive. May be that it is not the case.
Different points of view may bring that an API belongs to more than one class.
I suggest to use a TAG style classification to mark the API (an API can be tagged with one ore more tags)... the first tags may be the ones just identified

Marco Signorelli (TIM)

**Comment by hdamker** [comment]
@TEF-RicardoSerr I suppose there is no need to transfer closed issues?
