### ISSUE TITLE
Network Info - scope enhancement for Device Status, Connectivity Insights, or New API Proposal?

### ISSUE THREAD

**Issue by Kevsy** [camaraproject/APIBacklog#61]
I proposed code for [Network Info](https://github.com/camaraproject/ConnectivityInsights/blob/main/code/API_definitions/network-info.yaml) in the the pre-release WIP of [Connectivity Insights](https://github.com/camaraproject/ConnectivityInsights) .

'Network Info' provides some basic information about a given device connection to the network, e.g. Network type (cellular 2.5G/4G/5G etc., fixed, Wi-Fi, satellite), Network Identifier (MNC/MCC and equivalents in other networks). My understanding is that this information would form part of the 'Device Quality Indicator' API, which sources information from other CAMARA APIs, including Connectivity Insights and Device Status.

As spotted by @hdamker this causes overlap with Device Status, so this issue is to agree whether network info:
1- is a Scope Enhancement for Connectivity Insights
2- is a Scope Enhancement for Device Status
3- is a New API Proposal

I have no firm preference, although I do believe Network Info is useful - I have heard feedback from developers that 'different networks (including MVNOs) have different behaviours, that we learn over time - so it is good to know which network type and provider.' . I'm happy to support wherever it ends up.

Further context: Connectivity Insights [48](https://github.com/camaraproject/ConnectivityInsights/issues/48#issuecomment-2186582595) and Device Status [143](https://github.com/camaraproject/DeviceStatus/issues/143#issuecomment-2180573172)

**Comment by Kevsy** [comment]
Agreed in [API Backlog call 11th July](https://wiki.camaraproject.org/display/CAM/DeviceStatus) to raise a scope enhancement to Device Status, done if #66

**Comment by TEF-RicardoSerr** [comment]
As the outcome for this issue is refered in #66 guess this issue can be closed
