### ISSUE TITLE
Scope Enhancement: network info for Device Status API Family

### ISSUE THREAD

**Issue by Kevsy** [camaraproject/APIBacklog#66]
# API Scope Enhancement

| **Field** | Description | 
| ---- | ----- |
| API name | [DeviceStatus](https://github.com/camaraproject/DeviceStatus) |
| New API name | NetworkInfo |
| Scope Enhancement owner | Vodafone |
| Scope Enhancement summary | Read-only API to return the name of the operator and network type for an identified network-connected device. Business cases (1) developers can account for the different behaviours they have historically encountered from different network operators (2) developers can determine if the connection is to a virtual operator, which may result in different network capabilities (3) knowing the type of the network the device is connected to (cellular network type, fixed/Wi-Fi, satellite) allows the developer to better estimate network stability. Overall each business case can help improve end user experience|
| Technical viability |  Operator name is static, connection type is available from via NEF. 
| Commercial viability | Server implementations not known - but MNC/MCC lookup available on the UE via programmatic lookup to OS libraries.|
| YAML code available? | YES |
| Validated in lab/productive environments? | NO. |
| Validated with real customers? | NO.|
| Validated with operators? |NO.  |
| Supporters in API Backlog Working Group | Vodafone, Deutsche Telekom  |

**Comment by Kevsy** [comment]
Submitted as per action from [API Backlog call 11th July](https://wiki.camaraproject.org/display/CAM/DeviceStatus)

@NoelWirzius please let me know any changes needed

**Comment by NoelWirzius** [comment]
@Kevsy  lgtm 
@gmuratk would be great if you compare this to your proposal in Device Status

**Comment by jgarciahospital** [comment]
As discussed in https://github.com/camaraproject/APIBacklog/pull/72#issuecomment-2302131384, pending to clarify final destination of the proposal

**Comment by Kevsy** [comment]
Please can the team advise whether this capability to provide more granular data connection information (2G/3G/4G/5G/Wi-Fi etc. plus MNO/MNC/operator identifier) should be a separate API within the Device Status family, or a scope enhancement to extend CONNECTED_DATA?

This topic relates to open issue [66](https://github.com/camaraproject/APIBacklog/issues/66) and [PR 72](https://github.com/camaraproject/APIBacklog/pull/72) in APIBacklog , so your decision much appreciated :)
