### ISSUE TITLE
New API Proposal - Quality by Design

### ISSUE THREAD

**Issue by benhepworth** [camaraproject/APIBacklog#70]
Proposal for a new API in the Home Device family. The Quality by Demand API allows applications to:
- report application KPIs to network operator
- receive QbD score
- receive root cause analysis and recommended corrective actions
- request service improvements

Related to #71

**Comment by benhepworth** [comment]
What do we need to do to get on the agenda of the API Backlog call for next week for this proposal? (7/25 meeting)

**Comment by TEF-RicardoSerr** [comment]
Please Provide names, roles and github user for the recently created group

**Comment by benhepworth** [comment]
Owners will be: Ben Hepworth from CableLabs (me), Mahesh from Verizon, and Kevin Smith from Vodaphone
Maintainers will be the same 3 but will also include Randy Levansalor and Shafi Khan from CableLabs

**Comment by benhepworth** [comment]
PR submitted to update code owners and maintainers: https://github.com/camaraproject/QualityByDesign/pull/4
