### ISSUE TITLE
New API Proposal - IoT SMS send

### ISSUE THREAD

**Issue by chenfr2-ChinaTelecom** [camaraproject/APIBacklog#97]
Proposal to create "IoT SMS send" API:
This API allows customers to send SMS messages to their IoT SIM cards to remotely wake up and operate end devices, providing a convenient and efficient tool for remote device management.
Use case: keyless unlocking of car doors, remote control of air conditioning switch

**Comment by jgarciahospital** [comment]
As agreed in https://lf-camaraproject.atlassian.net/wiki/spaces/CAM/pages/46268427/2024-11-28+API+backlog+minutes, this proposal is withdrawn.
